version: '3'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: /bin/bash -c "bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
